Update description.ru.yml
hexlet-basics/exercises-javascript pull request #500
Opened 2021-08-08 15:01 UTC by yana-atrashkevich

Здравствуйте. На мой взгляд, необходимо добавить информацию о том, что можно конкатенировать прямо в console.log.
Так новичкам будет легче выполнять задание) 
Спасибо))

2021-08-09 13:39 UTC, frontstall commented on modules/30-variables/18-variable-concatenation/description.ru.yml
> +  console.log(intro + '\n' + info);
Чтобы использовать intro и info, из нужно сперва объявить, иначе непонятно, откуда они взялись. Код необходимо заключить в бектики с обозначением языка, на котором написан код (чтобы код был правильно опознан и раскрашен – см.примеры выше)

2021-08-09 13:40 UTC, frontstall requested changes

2021-08-09 13:40 UTC, frontstall commented on modules/30-variables/18-variable-concatenation/description.ru.yml
> +  console.log(intro + '\n' + info);
Чтобы использовать intro и info, из нужно сперва объявить, иначе непонятно, откуда они взялись. Код необходимо заключить в бектики с обозначением языка, на котором написан код (чтобы код был правильно опознан и раскрашен – см.примеры выше)

2021-08-10 07:04 UTC, mokevnin commented
Тема выражений внутри вызова функций проходится позже.

> Так новичкам будет легче выполнять задание)

Практика задумана так, чтобы новички отрабатывали работу с переменными. Легче тут уже некуда, это и так максимально просто.

2021-08-10 07:04 UTC, closed without merging